import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import Bannner from "@/components/Layout/Banner/Banner";
import Navbar from "@/components/Layout/Navbar/Navbar";
import Cursor from "@/components/Layout/CustomCursor/Cursor";
import Footer from "@/components/Layout/Footer/Footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable:"--font-inter",
  subsets:["latin"],
  weight:["400","600","700",]
})

export const metadata = {
  title: "vardaan farms",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} antialiased overflow-x-hidden`}
        id="body"
      >
        <main className="overflow-x-hidden">
          <Cursor />
          <Bannner />
          <Navbar />
          {children}
          <Footer/>
        </main>
      </body>
    </html>
  );
}
